<a href="https://colab.research.google.com/github/FunNyLuAz/Scripts-Universidade/blob/main/Python/Performance%20em%20Sistemas%20Ciberf%C3%ADsicos/05/Multiply%20Matrices/Multiply%20Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Multiplicar duas matrizes 3x3

Python


In [ ]:
def multiplyMatrices(matrixA, matrixB):
  matrix = list()
  n = len(matrixB)
  for i in range(len(matrixA)):
    matrix.append(list())
    for j in range(len(matrixB[0])):
      matrix[i].append(0)
      for p in range(n):
        matrix[i][j] += matrixA[i][p] * matrixB[p][j]
  return matrix


matrixA = [
  [1, 2, 2],
  [2, 3, 2],
  [2, 2, 2],
  [1, 2, 2]
]
matrixB = [
  [0, 1, 0, 2],
  [0, 0, 1, 2],
  [0, 1, 0, 1]
]

multiplyMatrices(matrixA, matrixB)

[[0, 3, 2, 8], [0, 4, 3, 12], [0, 4, 2, 10], [0, 3, 2, 8]]

Numpy

In [ ]:
import numpy


matrixA = numpy.array([
  [1, 2, 2],
  [2, 3, 2],
  [2, 2, 2],
  [1, 2, 2]
])
matrixB = numpy.array([
  [0, 1, 0, 2],
  [0, 0, 1, 2],
  [0, 1, 0, 1]
])

numpy.matmul(matrixA, matrixB)

array([[ 0,  3,  2,  8],
       [ 0,  4,  3, 12],
       [ 0,  4,  2, 10],
       [ 0,  3,  2,  8]])

Jax

In [ ]:
import jax.numpy as jnp


matrixA = jnp.array([
  [1, 2, 2],
  [2, 3, 2],
  [2, 2, 2],
  [1, 2, 2]
])
matrixB = jnp.array([
  [0, 1, 0, 2],
  [0, 0, 1, 2],
  [0, 1, 0, 1]
])

jnp.matmul(matrixA, matrixB)

DeviceArray([[ 0,  3,  2,  8],
             [ 0,  4,  3, 12],
             [ 0,  4,  2, 10],
             [ 0,  3,  2,  8]], dtype=int32)

TensorFlow

In [ ]:
import tensorflow


matrixA = tensorflow.constant([
  1, 2, 2,
  2, 3, 2,
  2, 2, 2,
  1, 2, 2
], shape=(4, 3))
matrixB = tensorflow.constant([
  0, 1, 0, 2,
  0, 0, 1, 2,
  0, 1, 0, 1
], shape=(3, 4))

tensorflow.linalg.matmul(matrixA, matrixB)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  3,  2,  8],
       [ 0,  4,  3, 12],
       [ 0,  4,  2, 10],
       [ 0,  3,  2,  8]], dtype=int32)>

# 2. Medir o tempo para multiplicar duas matrizes 1000x1000 completas com 1

Python


In [ ]:
import time


def multiplyMatrices(matrixA, matrixB):
  matrix = list()
  n = len(matrixB)
  for i in range(len(matrixA)):
    matrix.append(list())
    for j in range(len(matrixB[0])):
      matrix[i].append(0)
      for p in range(n):
        matrix[i][j] += matrixA[i][p] * matrixB[p][j]
  return matrix


matrixA = list()
for i in range(1000):
  matrixA.append(list())
  for j in range(1000):
    matrixA[i].append(1)
matrixB = list()
for i in range(1000):
  matrixB.append(list())
  for j in range(1000):
    matrixB[i].append(1)

intiallTime = time.time_ns()
multiplyMatrices(matrixA, matrixB)
endTime = time.time_ns()
print(f"Demorou {endTime - intiallTime}ns.")

Demorou 303116519900ns.


Numpy

In [ ]:
import time
import numpy


matrixA = numpy.full((1000, 1000), 1)
matrixB = numpy.full((1000, 1000), 1)

intiallTime = time.time_ns()
numpy.matmul(matrixA, matrixB)
endTime = time.time_ns()
print(f"Demorou {endTime - intiallTime}ns.")

Demorou 4325107130ns.


Jax

In [ ]:
import time
import jax.numpy as jnp


matrixA = jnp.full((1000, 1000), 1)
matrixB = jnp.full((1000, 1000), 1)

intiallTime = time.time_ns()
jnp.matmul(matrixA, matrixB)
endTime = time.time_ns()
print(f"Demorou {endTime - intiallTime}ns.")

Demorou 379719405ns.


TensorFlow

In [ ]:
import time
import tensorflow


matrixA = tensorflow.fill((1000, 1000), 1)
matrixB = tensorflow.fill((1000, 1000), 1)

intiallTime = time.time_ns()
tensorflow.linalg.matmul(matrixA, matrixB)
endTime = time.time_ns()
print(f"Demorou {endTime - intiallTime}ns.")

Demorou 307326099ns.
